<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types. It is used by the
| Upload class to help identify allowed file types.
|
*/

$mimes = array(	'hqx'	=>	'megapublik/mac-binhex40',
				'cpt'	=>	'megapublik/mac-compactpro',
				'csv'	=>	array('text/x-comma-separated-values', 'text/comma-separated-values', 'megapublik/octet-stream', 'megapublik/vnd.ms-excel', 'text/x-csv', 'text/csv', 'megapublik/csv', 'megapublik/excel', 'megapublik/vnd.msexcel'),
				'bin'	=>	'megapublik/macbinary',
				'dms'	=>	'megapublik/octet-stream',
				'lha'	=>	'megapublik/octet-stream',
				'lzh'	=>	'megapublik/octet-stream',
				'exe'	=>	array('megapublik/octet-stream', 'megapublik/x-msdownload'),
				'class'	=>	'megapublik/octet-stream',
				'psd'	=>	'megapublik/x-photoshop',
				'so'	=>	'megapublik/octet-stream',
				'sea'	=>	'megapublik/octet-stream',
				'dll'	=>	'megapublik/octet-stream',
				'oda'	=>	'megapublik/oda',
				'pdf'	=>	array('megapublik/pdf', 'megapublik/x-download'),
				'ai'	=>	'megapublik/postscript',
				'eps'	=>	'megapublik/postscript',
				'ps'	=>	'megapublik/postscript',
				'smi'	=>	'megapublik/smil',
				'smil'	=>	'megapublik/smil',
				'mif'	=>	'megapublik/vnd.mif',
				'xls'	=>	array('megapublik/excel', 'megapublik/vnd.ms-excel', 'megapublik/msexcel'),
				'ppt'	=>	array('megapublik/powerpoint', 'megapublik/vnd.ms-powerpoint'),
				'wbxml'	=>	'megapublik/wbxml',
				'wmlc'	=>	'megapublik/wmlc',
				'dcr'	=>	'megapublik/x-director',
				'dir'	=>	'megapublik/x-director',
				'dxr'	=>	'megapublik/x-director',
				'dvi'	=>	'megapublik/x-dvi',
				'gtar'	=>	'megapublik/x-gtar',
				'gz'	=>	'megapublik/x-gzip',
				'php'	=>	'megapublik/x-httpd-php',
				'php4'	=>	'megapublik/x-httpd-php',
				'php3'	=>	'megapublik/x-httpd-php',
				'phtml'	=>	'megapublik/x-httpd-php',
				'phps'	=>	'megapublik/x-httpd-php-source',
				'js'	=>	'megapublik/x-javascript',
				'swf'	=>	'megapublik/x-shockwave-flash',
				'sit'	=>	'megapublik/x-stuffit',
				'tar'	=>	'megapublik/x-tar',
				'tgz'	=>	array('megapublik/x-tar', 'megapublik/x-gzip-compressed'),
				'xhtml'	=>	'megapublik/xhtml+xml',
				'xht'	=>	'megapublik/xhtml+xml',
				'zip'	=> array('megapublik/x-zip', 'megapublik/zip', 'megapublik/x-zip-compressed'),
				'mid'	=>	'audio/midi',
				'midi'	=>	'audio/midi',
				'mpga'	=>	'audio/mpeg',
				'mp2'	=>	'audio/mpeg',
				'mp3'	=>	array('audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'),
				'aif'	=>	'audio/x-aiff',
				'aiff'	=>	'audio/x-aiff',
				'aifc'	=>	'audio/x-aiff',
				'ram'	=>	'audio/x-pn-realaudio',
				'rm'	=>	'audio/x-pn-realaudio',
				'rpm'	=>	'audio/x-pn-realaudio-plugin',
				'ra'	=>	'audio/x-realaudio',
				'rv'	=>	'video/vnd.rn-realvideo',
				'wav'	=>	'audio/x-wav',
				'bmp'	=>	'image/bmp',
				'gif'	=>	'image/gif',
				'jpeg'	=>	array('image/jpeg', 'image/pjpeg'),
				'jpg'	=>	array('image/jpeg', 'image/pjpeg'),
				'jpe'	=>	array('image/jpeg', 'image/pjpeg'),
				'png'	=>	array('image/png', 'image/x-png'),
				'tiff'	=>	'image/tiff',
				'tif'	=>	'image/tiff',
				'css'	=>	'text/css',
				'html'	=>	'text/html',
				'htm'	=>	'text/html',
				'shtml'	=>	'text/html',
				'txt'	=>	'text/plain',
				'text'	=>	'text/plain',
				'log'	=>	array('text/plain', 'text/x-log'),
				'rtx'	=>	'text/richtext',
				'rtf'	=>	'text/rtf',
				'xml'	=>	'text/xml',
				'xsl'	=>	'text/xml',
				'mpeg'	=>	'video/mpeg',
				'mpg'	=>	'video/mpeg',
				'mpe'	=>	'video/mpeg',
				'qt'	=>	'video/quicktime',
				'mov'	=>	'video/quicktime',
				'avi'	=>	'video/x-msvideo',
				'movie'	=>	'video/x-sgi-movie',
				'doc'	=>	'megapublik/msword',
				'docx'	=>	'megapublik/vnd.openxmlformats-officedocument.wordprocessingml.document',
				'xlsx'	=>	'megapublik/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
				'word'	=>	array('megapublik/msword', 'megapublik/octet-stream'),
				'xl'	=>	'megapublik/excel',
				'eml'	=>	'message/rfc822',
				'json' => array('megapublik/json', 'text/json')
			);


/* End of file mimes.php */
/* Location: ./megapublik/config/mimes.php */