<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['states']	= array(
	1 => array('name' => 'País Vasco', 'borders' => array(4, 5, 6, 7), 'timezone' => 'Europe/Madrid'),
	2 => array('name' => 'Galicia', 'borders' => array(3, 6), 'timezone' => 'Europe/Madrid'),
	3 => array('name' => 'Asturias', 'borders' => array(2, 4, 6), 'timezone' => 'Europe/Madrid'),
	4 => array('name' => 'Cantabria', 'borders' => array(1, 3, 6), 'timezone' => 'Europe/Madrid'),
	5 => array('name' => 'Navarra', 'borders' => array(1, 7, 8), 'timezone' => 'Europe/Madrid'),
	6 => array('name' => 'Castilla y Leon', 'borders' => array(1, 2, 3, 4, 5, 7, 8, 10, 11, 12), 'timezone' => 'Europe/Madrid'),
	7 => array('name' => 'La Rioja', 'borders' => array(1, 5, 6, 8), 'timezone' => 'Europe/Madrid'),
	8 => array('name' => 'Aragón', 'borders' => array(5, 6, 7, 9, 12, 13), 'timezone' => 'Europe/Madrid'),
	9 => array('name' => 'Cataluña', 'borders' => array(8, 13, 16), 'timezone' => 'Europe/Madrid'),
	10 => array('name' => 'Extremadura', 'borders' => array(6, 12, 14), 'timezone' => 'Europe/Madrid'),
	11 => array('name' => 'Comunidad de Madrid', 'borders' => array(6, 12), 'timezone' => 'Europe/Madrid'),
	12 => array('name' => 'Castilla la Mancha', 'borders' => array(6, 8, 10, 11, 13, 14, 15), 'timezone' => 'Europe/Madrid'),
	13 => array('name' => 'Comunidad Valenciana', 'borders' => array(8, 9, 12, 15, 16), 'timezone' => 'Europe/Madrid'),
	14 => array('name' => 'Andalucía', 'borders' => array(10, 12, 15, 17, 18, 19), 'timezone' => 'Europe/Madrid'),
	15 => array('name' => 'Región de Murcia', 'borders' => array(12, 13, 14), 'timezone' => 'Europe/Madrid'),
	16 => array('name' => 'Islas Baleares', 'borders' => array(9, 13), 'timezone' => 'Europe/Madrid'),
	17 => array('name' => 'Ceuta', 'borders' => array(14), 'timezone' => 'Europe/Madrid'),
	18 => array('name' => 'Melilla', 'borders' => array(14), 'timezone' => 'Europe/Madrid'),
	19 => array('name' => 'Islas Canarias', 'borders' => array(14), 'timezone' => 'Atlantic/Canary'),
	20 => array('name' => 'Greater London', 'borders' => array(30, 31), 'timezone' => 'Europe/London'),
	21 => array('name' => 'Northern Ireland', 'borders' => array(22, 24, 26), 'timezone' => 'Europe/Belfast'),
	22 => array('name' => 'Scotland', 'borders' => array(21, 23, 24), 'timezone' => 'Europe/London'),
	23 => array('name' => 'North East England', 'borders' => array(22, 24, 25), 'timezone' => 'Europe/London'),
	24 => array('name' => 'North West England', 'borders' => array(21, 22, 23, 25, 26, 27, 28), 'timezone' => 'Europe/London'),
	25 => array('name' => 'Yorkshire And The Humber', 'borders' => array(24, 23, 28), 'timezone' => 'Europe/London'),
	26 => array('name' => 'Wales', 'borders' => array(21, 24, 27, 29), 'timezone' => 'Europe/London'),
	27 => array('name' => 'West Midlands', 'borders' => array(24, 26, 28, 29, 30), 'timezone' => 'Europe/London'),
	28 => array('name' => 'East Midlands', 'borders' => array(24, 25, 27, 30, 31), 'timezone' => 'Europe/London'),
	29 => array('name' => 'South West England', 'borders' => array(26, 27, 30), 'timezone' => 'Europe/London'),
	30 => array('name' => 'South East England', 'borders' => array(20, 28, 29, 31), 'timezone' => 'Europe/London'),
	31 => array('name' => 'East Of England', 'borders' => array(20, 28, 30), 'timezone' => 'Europe/London')
);